name: Pack Docker Image
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull golang:1.22-alpine
          docker save golang:1.22-alpine -o go_image.tar
      - name: Upload Zip Archive
        uses: actions/upload-artifact@v4
        with:
          name: docker-tarball
          path: go_image.tar
