name: Pack Docker Image
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull kubernetesui/dashboard-api:latest
          docker save kubernetesui/dashboard-api:latest -o temp.tar
      - name: Upload Zip Archive
        uses: actions/upload-artifact@v4
        with:
          name: docker-tarball
          path: temp.tar
k
